
GET {{baseUrl}}/oauth/v1/generate?grant_type=client_credentials
Authorization: Basic {{authorization}}

###
POST {{baseUrl}}/mpesa/c2b/v1/simulate
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{    
   "CommandID": "CustomerPayBillOnline",
   "Amount":"10",
   "Msisdn":"254724628580",
   "BillRefNumber":"00000",
   "ShortCode":"600247"
}

###
POST {{baseUrl}}/mpesa/stkpush/v1/processrequest
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{    
   "BusinessShortCode":"174379",    
   "Password": "MTc0Mzc5YmZiMjc5ZjlhYTliZGJjZjE1OGU5N2RkNzFhNDY3Y2QyZTBjODkzMDU5YjEwZjc4ZTZiNzJhZGExZWQyYzkxOTIwMTYwMjE2MTY1NjI3",    
 "Timestamp":"20160216165627",    
 "TransactionType": "CustomerPayBillOnline",    
   "Amount":"1",    
  "PartyA":"254708374149",    
   "PartyB":"174379",    
 "PhoneNumber":"254708374149",    
 "CallBackURL":"https://mydomain.com/pat",    
 "AccountReference":"Test",    
 "TransactionDesc":"Test"
}